workspace_password = "my-super-secret-password"
aws_region         = "us-east-1"
aws_access_key     = "my-access-key"
aws_secret_key     = "my-secret-key"
aws_directory_name = "workspaces.illumidesk.com"
