workspace_password = "workspace-password"
aws_region         = "aws-region"
aws_access_key     = "your-key-id"
aws_secret_key     = "your-secret-key"
aws_directory_name = "workspaces-sub-domain.domain.tld"
